name: server

networks:
  intranet:
    driver: bridge
    name: intranet

include:
  - path: cloudflare/docker-compose.yaml
  - path: nginx/docker-compose.yaml
  - path: nextcloud/docker-compose.yaml
  - path: portainer/docker-compose.yaml
  - path: jellyfin/docker-compose.yaml
  - path: gitea/docker-compose.yaml
  - path: expresso/docker-compose.yaml
