name: gitea

services:
  gitea:
    image: gitea/gitea:1.22.0
    container_name: gitea
    networks:
      - intranet
    environment:
      - USER_UID=108
      - USER_GID=110
    restart: always
    volumes:
      - ${BASE_DIR}/data:/data
      - /home/git/.ssh:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea_db
    env_file:
      - .env

  gitea_db:
    image: postgres:14
    container_name: gitea_db
    restart: always
    networks:
      - intranet
    volumes:
      - ${BASE_DIR}/db:/var/lib/postgresql/data
    env_file:
      - .env
